### ISSUE TITLE
Contacter météofrance pour la récupération de données (API)

### ISSUE THREAD

**Issue by MolerEmeric** [Logy16/automatisationDesDonneesFDF#1]
Faire une réunion avec météoFrance pour avoir la documentation et définir la stratégie de récupération des informations

**Comment by Romaiiin81** [comment]
Prise de contact le 05/01 avec Romaric Cinotti, responsable de l'assistance feux de forêt zone sud Météo France.

**Comment by Romaiiin81** [comment]
Relance par appel et par mail plusieurs fois jusqu'au 19 janvier

**Comment by Romaiiin81** [comment]
Réponse le 20/01 : Voir avec la DGSCGC en contactant Fabrice Chassagne

**Comment by Romaiiin81** [comment]
Relance 27/01
